'''b) Initialize the turtle canvas and draw 4 circle with different radius with color , “red”, “blue” ” ,” yellow” , “green”'''
import turtle
turtle.color("red")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.color("blue")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.color("yellow")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
turtle.penup()
turtle.forward(70)
turtle.pendown()
turtle.color("green")
turtle.begin_fill()
turtle.circle(40)
turtle.end_fill()
